name: MultiPublish
description: Automatically publish JS modules (supports multiple modules, respects .npmrc)
author: Author.io
branding:
  icon: box
  color: red
inputs:
  scan:
    description: Optional. Specify which directories (relative to the root) should be scanned for modules. Comma separated, supports glob syntax.
    required: false
    default: './elements'
  registry:
    description: Optional. Specify what registry should be used.
    required: false
  npmrc-options:
    description: Optional. Specify the npmrc options.
    required: false
  single-element: 
    description: Optional. When publishing a single element only the patch version will be increased. Any other version variables will be ignored.
    default: 'false'
    required: false
outputs:
  modules:
    description: "A comma-delimited list of modules that were updated. Ex: '@myorg/mypkg@1.0.0, @myorg/myotherpkg@1.4.1'"
runs:
  using: "node12"
  main: "lib/main.js"
